// Code generated by protoc-gen-go.
// source: behaviour_log.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	behaviour_log.proto

It has these top-level messages:
	Behaviour
	BehaviourCreateRole
	BehaviourView
	BehaviourGuide
	BehaviourExp
	BehaviourBattle
	BehaviourActivity
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type BehaviourType int32

const (
	BehaviourType_CreateRole BehaviourType = 1
	BehaviourType_View       BehaviourType = 2
	BehaviourType_Guide      BehaviourType = 3
	BehaviourType_Exp        BehaviourType = 4
	BehaviourType_Battle     BehaviourType = 5
	BehaviourType_Activity   BehaviourType = 6
)

var BehaviourType_name = map[int32]string{
	1: "CreateRole",
	2: "View",
	3: "Guide",
	4: "Exp",
	5: "Battle",
	6: "Activity",
}
var BehaviourType_value = map[string]int32{
	"CreateRole": 1,
	"View":       2,
	"Guide":      3,
	"Exp":        4,
	"Battle":     5,
	"Activity":   6,
}

func (x BehaviourType) Enum() *BehaviourType {
	p := new(BehaviourType)
	*p = x
	return p
}
func (x BehaviourType) String() string {
	return proto1.EnumName(BehaviourType_name, int32(x))
}
func (x *BehaviourType) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(BehaviourType_value, data, "BehaviourType")
	if err != nil {
		return err
	}
	*x = BehaviourType(value)
	return nil
}
func (BehaviourType) EnumDescriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{0} }

// 活动类型
type ActivityType int32

const (
	ActivityType_MonthSignIn  ActivityType = 1
	ActivityType_GiftExchange ActivityType = 2
	ActivityType_GiftOnline   ActivityType = 3
	ActivityType_Logn30       ActivityType = 4
	ActivityType_LoginHaoLi   ActivityType = 5
)

var ActivityType_name = map[int32]string{
	1: "MonthSignIn",
	2: "GiftExchange",
	3: "GiftOnline",
	4: "Logn30",
	5: "LoginHaoLi",
}
var ActivityType_value = map[string]int32{
	"MonthSignIn":  1,
	"GiftExchange": 2,
	"GiftOnline":   3,
	"Logn30":       4,
	"LoginHaoLi":   5,
}

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}
func (x ActivityType) String() string {
	return proto1.EnumName(ActivityType_name, int32(x))
}
func (x *ActivityType) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(ActivityType_value, data, "ActivityType")
	if err != nil {
		return err
	}
	*x = ActivityType(value)
	return nil
}
func (ActivityType) EnumDescriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{1} }

// 行为数据
type Behaviour struct {
	Type             *BehaviourType       `protobuf:"varint,1,req,name=type,enum=BehaviourType" json:"type,omitempty"`
	CreateRole       *BehaviourCreateRole `protobuf:"bytes,2,opt,name=createRole" json:"createRole,omitempty"`
	View             *BehaviourView       `protobuf:"bytes,3,opt,name=view" json:"view,omitempty"`
	Guide            *BehaviourGuide      `protobuf:"bytes,4,opt,name=guide" json:"guide,omitempty"`
	Exp              *BehaviourExp        `protobuf:"bytes,5,opt,name=exp" json:"exp,omitempty"`
	Battle           *BehaviourBattle     `protobuf:"bytes,6,opt,name=battle" json:"battle,omitempty"`
	Activity         *BehaviourActivity   `protobuf:"bytes,7,opt,name=activity" json:"activity,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Behaviour) Reset()                    { *m = Behaviour{} }
func (m *Behaviour) String() string            { return proto1.CompactTextString(m) }
func (*Behaviour) ProtoMessage()               {}
func (*Behaviour) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{0} }

func (m *Behaviour) GetType() BehaviourType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return BehaviourType_CreateRole
}

func (m *Behaviour) GetCreateRole() *BehaviourCreateRole {
	if m != nil {
		return m.CreateRole
	}
	return nil
}

func (m *Behaviour) GetView() *BehaviourView {
	if m != nil {
		return m.View
	}
	return nil
}

func (m *Behaviour) GetGuide() *BehaviourGuide {
	if m != nil {
		return m.Guide
	}
	return nil
}

func (m *Behaviour) GetExp() *BehaviourExp {
	if m != nil {
		return m.Exp
	}
	return nil
}

func (m *Behaviour) GetBattle() *BehaviourBattle {
	if m != nil {
		return m.Battle
	}
	return nil
}

func (m *Behaviour) GetActivity() *BehaviourActivity {
	if m != nil {
		return m.Activity
	}
	return nil
}

// 日志行为: 创建账号
type BehaviourCreateRole struct {
	UserId           *int32  `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Platform         *string `protobuf:"bytes,3,req,name=platform" json:"platform,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BehaviourCreateRole) Reset()                    { *m = BehaviourCreateRole{} }
func (m *BehaviourCreateRole) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourCreateRole) ProtoMessage()               {}
func (*BehaviourCreateRole) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{1} }

func (m *BehaviourCreateRole) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourCreateRole) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BehaviourCreateRole) GetPlatform() string {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ""
}

// 日志行为: 页面跳转
type BehaviourView struct {
	UserId           *int32 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	ViewId           *int32 `protobuf:"varint,2,req,name=viewId" json:"viewId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BehaviourView) Reset()                    { *m = BehaviourView{} }
func (m *BehaviourView) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourView) ProtoMessage()               {}
func (*BehaviourView) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{2} }

func (m *BehaviourView) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourView) GetViewId() int32 {
	if m != nil && m.ViewId != nil {
		return *m.ViewId
	}
	return 0
}

// 日志行为：新手引导进度
type BehaviourGuide struct {
	UserId           *int32 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	GuideId          *int32 `protobuf:"varint,2,req,name=guideId" json:"guideId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BehaviourGuide) Reset()                    { *m = BehaviourGuide{} }
func (m *BehaviourGuide) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourGuide) ProtoMessage()               {}
func (*BehaviourGuide) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{3} }

func (m *BehaviourGuide) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourGuide) GetGuideId() int32 {
	if m != nil && m.GuideId != nil {
		return *m.GuideId
	}
	return 0
}

// 日志行为：经验
type BehaviourExp struct {
	UserId           *int32 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Exp              *int32 `protobuf:"varint,3,req,name=exp" json:"exp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BehaviourExp) Reset()                    { *m = BehaviourExp{} }
func (m *BehaviourExp) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourExp) ProtoMessage()               {}
func (*BehaviourExp) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{4} }

func (m *BehaviourExp) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourExp) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *BehaviourExp) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

// 日志行为：推图进度
type BehaviourBattle struct {
	UserId           *int32 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	BattleId         *int32 `protobuf:"varint,2,req,name=battleId" json:"battleId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BehaviourBattle) Reset()                    { *m = BehaviourBattle{} }
func (m *BehaviourBattle) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourBattle) ProtoMessage()               {}
func (*BehaviourBattle) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{5} }

func (m *BehaviourBattle) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourBattle) GetBattleId() int32 {
	if m != nil && m.BattleId != nil {
		return *m.BattleId
	}
	return 0
}

// 日志行为：活动记录
type BehaviourActivity struct {
	UserId           *int32        `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	Type             *ActivityType `protobuf:"varint,2,req,name=type,enum=ActivityType" json:"type,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *BehaviourActivity) Reset()                    { *m = BehaviourActivity{} }
func (m *BehaviourActivity) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourActivity) ProtoMessage()               {}
func (*BehaviourActivity) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{6} }

func (m *BehaviourActivity) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourActivity) GetType() ActivityType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ActivityType_MonthSignIn
}

func init() {
	proto1.RegisterType((*Behaviour)(nil), "Behaviour")
	proto1.RegisterType((*BehaviourCreateRole)(nil), "BehaviourCreateRole")
	proto1.RegisterType((*BehaviourView)(nil), "BehaviourView")
	proto1.RegisterType((*BehaviourGuide)(nil), "BehaviourGuide")
	proto1.RegisterType((*BehaviourExp)(nil), "BehaviourExp")
	proto1.RegisterType((*BehaviourBattle)(nil), "BehaviourBattle")
	proto1.RegisterType((*BehaviourActivity)(nil), "BehaviourActivity")
	proto1.RegisterEnum("BehaviourType", BehaviourType_name, BehaviourType_value)
	proto1.RegisterEnum("ActivityType", ActivityType_name, ActivityType_value)
}

var behaviour_log_fileDescriptor0 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x93, 0xdd, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0xd5, 0x7c, 0xb5, 0xbd, 0x6d, 0x53, 0xe3, 0xf1, 0x10, 0x31, 0x84, 0xaa, 0x8a, 0x87,
	0x6a, 0x0f, 0x01, 0x36, 0xf1, 0xc2, 0x13, 0x14, 0x55, 0x63, 0xd2, 0x10, 0x12, 0x20, 0x90, 0x90,
	0xd0, 0xe4, 0xa6, 0x5e, 0x6a, 0x29, 0xb5, 0x43, 0x70, 0x3f, 0xf6, 0x87, 0xf3, 0xce, 0xb5, 0xb3,
	0x26, 0x5d, 0xba, 0xb7, 0xfa, 0x9c, 0x7b, 0xcf, 0xf5, 0xfd, 0xd5, 0x81, 0x93, 0x39, 0x5f, 0xb2,
	0x8d, 0x50, 0xeb, 0xe2, 0x26, 0x53, 0x69, 0x9c, 0x17, 0x4a, 0xab, 0xf1, 0xbf, 0x16, 0x74, 0xa7,
	0x7b, 0x9d, 0x3e, 0x07, 0x4f, 0xdf, 0xe5, 0x3c, 0x6a, 0x8d, 0x9c, 0x49, 0x78, 0x1e, 0xc6, 0x95,
	0xf3, 0x1d, 0x55, 0x3a, 0x01, 0x48, 0x0a, 0xce, 0x34, 0xff, 0xaa, 0x32, 0x1e, 0x39, 0xa3, 0xd6,
	0xa4, 0x77, 0xfe, 0xb4, 0xae, 0xf9, 0x58, 0x79, 0x26, 0x67, 0x23, 0xf8, 0x36, 0x72, 0x6d, 0xcd,
	0x41, 0xce, 0x0f, 0x54, 0xe9, 0x0b, 0xf0, 0xd3, 0xb5, 0x58, 0xf0, 0xc8, 0xb3, 0xf6, 0xb0, 0xb6,
	0x2f, 0x8d, 0x4c, 0x9f, 0x81, 0xcb, 0x77, 0x79, 0xe4, 0x5b, 0x77, 0x50, 0xbb, 0xb3, 0x5d, 0x4e,
	0x47, 0x10, 0xcc, 0x99, 0xd6, 0x38, 0x3f, 0xb0, 0x36, 0xa9, 0xed, 0xa9, 0xd5, 0xe9, 0x4b, 0xe8,
	0xb0, 0x44, 0x8b, 0x8d, 0xd0, 0x77, 0x51, 0xdb, 0xd6, 0xd0, 0xba, 0xe6, 0xc3, 0xbd, 0x33, 0x9e,
	0xc1, 0xc9, 0x63, 0x17, 0x0f, 0x21, 0x58, 0xff, 0xe5, 0xc5, 0xd5, 0xc2, 0x22, 0xf0, 0x69, 0x1f,
	0x3c, 0xc9, 0x56, 0x66, 0x59, 0x67, 0xd2, 0xa5, 0x04, 0x3a, 0x79, 0xc6, 0xf4, 0xad, 0x2a, 0x56,
	0xb8, 0x1a, 0x2a, 0xe3, 0x57, 0x30, 0x78, 0xb8, 0x5b, 0x33, 0x00, 0xcf, 0x86, 0x04, 0x9e, 0x4d,
	0x84, 0x3f, 0x7e, 0x03, 0x61, 0x63, 0xdb, 0x66, 0xc7, 0x10, 0xda, 0x96, 0x4e, 0xd5, 0xf2, 0x0e,
	0xfa, 0x0f, 0x10, 0x34, 0x1b, 0x06, 0xe0, 0x67, 0x7c, 0xc3, 0xb3, 0xb2, 0x9c, 0xf6, 0x4a, 0x7a,
	0xae, 0xed, 0xbd, 0x80, 0x61, 0x93, 0x4f, 0xb3, 0x1d, 0x97, 0x2a, 0x89, 0x56, 0x03, 0xdf, 0xc3,
	0x93, 0x23, 0x60, 0x47, 0x6d, 0xa7, 0xf7, 0x4f, 0xc5, 0xb1, 0x4f, 0x65, 0x10, 0xef, 0x0b, 0xcd,
	0x4b, 0x39, 0xfb, 0x79, 0x80, 0xc5, 0x3e, 0x9d, 0x10, 0xa0, 0xa6, 0x4c, 0x5a, 0xb4, 0x03, 0x9e,
	0xc1, 0x45, 0x1c, 0xda, 0x05, 0xdf, 0x72, 0x20, 0x2e, 0x6d, 0x83, 0x8b, 0xfb, 0x11, 0x8f, 0x02,
	0x04, 0xe5, 0x65, 0x89, 0xf9, 0x07, 0x3a, 0xfb, 0x68, 0x12, 0x9c, 0xfd, 0x86, 0xfe, 0xe1, 0x20,
	0x84, 0xd5, 0xfb, 0xac, 0xa4, 0x5e, 0x7e, 0x13, 0xa9, 0xbc, 0x92, 0x18, 0x4c, 0xa0, 0x7f, 0x29,
	0x6e, 0xf5, 0x6c, 0x97, 0x2c, 0x99, 0x4c, 0x39, 0x0e, 0xc0, 0xd1, 0x46, 0xf9, 0x22, 0x33, 0x21,
	0xcd, 0x14, 0x0c, 0xbf, 0x56, 0xa9, 0xbc, 0x78, 0x8d, 0x83, 0xd0, 0xc3, 0xdf, 0x42, 0x7e, 0x62,
	0xea, 0x5a, 0x10, 0x7f, 0xfa, 0x16, 0x4e, 0x13, 0xb5, 0x8a, 0xff, 0x88, 0x24, 0xde, 0xaa, 0x22,
	0x5b, 0x6c, 0xf1, 0x62, 0x18, 0xa4, 0xcb, 0x8f, 0x65, 0x5a, 0xb3, 0xc4, 0xae, 0x9b, 0x7c, 0xfe,
	0xcb, 0xb7, 0xfa, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0xb1, 0x05, 0x19, 0x5a, 0x03, 0x00,
	0x00,
}
