// Code generated by protoc-gen-go.
// source: behaviour_log.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	behaviour_log.proto

It has these top-level messages:
	Behaviour
	BehaviourCreateRole
	BehaviourView
	BehaviourGuide
	BehaviourExp
	BehaviourBattle
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type BehaviourType int32

const (
	BehaviourType_CreateRole BehaviourType = 1
	BehaviourType_View       BehaviourType = 2
	BehaviourType_Guide      BehaviourType = 3
	BehaviourType_Exp        BehaviourType = 4
	BehaviourType_Battle     BehaviourType = 5
)

var BehaviourType_name = map[int32]string{
	1: "CreateRole",
	2: "View",
	3: "Guide",
	4: "Exp",
	5: "Battle",
}
var BehaviourType_value = map[string]int32{
	"CreateRole": 1,
	"View":       2,
	"Guide":      3,
	"Exp":        4,
	"Battle":     5,
}

func (x BehaviourType) Enum() *BehaviourType {
	p := new(BehaviourType)
	*p = x
	return p
}
func (x BehaviourType) String() string {
	return proto1.EnumName(BehaviourType_name, int32(x))
}
func (x *BehaviourType) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(BehaviourType_value, data, "BehaviourType")
	if err != nil {
		return err
	}
	*x = BehaviourType(value)
	return nil
}
func (BehaviourType) EnumDescriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{0} }

// 行为数据
type Behaviour struct {
	Type             *BehaviourType       `protobuf:"varint,1,req,name=type,enum=BehaviourType" json:"type,omitempty"`
	CreateRole       *BehaviourCreateRole `protobuf:"bytes,2,opt,name=createRole" json:"createRole,omitempty"`
	View             *BehaviourView       `protobuf:"bytes,3,opt,name=view" json:"view,omitempty"`
	Guide            *BehaviourGuide      `protobuf:"bytes,4,opt,name=guide" json:"guide,omitempty"`
	Exp              *BehaviourExp        `protobuf:"bytes,5,opt,name=exp" json:"exp,omitempty"`
	Battle           *BehaviourBattle     `protobuf:"bytes,6,opt,name=battle" json:"battle,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Behaviour) Reset()                    { *m = Behaviour{} }
func (m *Behaviour) String() string            { return proto1.CompactTextString(m) }
func (*Behaviour) ProtoMessage()               {}
func (*Behaviour) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{0} }

func (m *Behaviour) GetType() BehaviourType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return BehaviourType_CreateRole
}

func (m *Behaviour) GetCreateRole() *BehaviourCreateRole {
	if m != nil {
		return m.CreateRole
	}
	return nil
}

func (m *Behaviour) GetView() *BehaviourView {
	if m != nil {
		return m.View
	}
	return nil
}

func (m *Behaviour) GetGuide() *BehaviourGuide {
	if m != nil {
		return m.Guide
	}
	return nil
}

func (m *Behaviour) GetExp() *BehaviourExp {
	if m != nil {
		return m.Exp
	}
	return nil
}

func (m *Behaviour) GetBattle() *BehaviourBattle {
	if m != nil {
		return m.Battle
	}
	return nil
}

// 日志行为: 创建账号
type BehaviourCreateRole struct {
	UserId           *int32  `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Platform         *string `protobuf:"bytes,3,req,name=platform" json:"platform,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BehaviourCreateRole) Reset()                    { *m = BehaviourCreateRole{} }
func (m *BehaviourCreateRole) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourCreateRole) ProtoMessage()               {}
func (*BehaviourCreateRole) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{1} }

func (m *BehaviourCreateRole) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourCreateRole) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BehaviourCreateRole) GetPlatform() string {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ""
}

// 日志行为: 页面跳转
type BehaviourView struct {
	UserId           *int32 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	ViewId           *int32 `protobuf:"varint,2,req,name=viewId" json:"viewId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BehaviourView) Reset()                    { *m = BehaviourView{} }
func (m *BehaviourView) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourView) ProtoMessage()               {}
func (*BehaviourView) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{2} }

func (m *BehaviourView) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourView) GetViewId() int32 {
	if m != nil && m.ViewId != nil {
		return *m.ViewId
	}
	return 0
}

// 日志行为：新手引导进度
type BehaviourGuide struct {
	UserId           *int32 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	GuideId          *int32 `protobuf:"varint,2,req,name=guideId" json:"guideId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BehaviourGuide) Reset()                    { *m = BehaviourGuide{} }
func (m *BehaviourGuide) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourGuide) ProtoMessage()               {}
func (*BehaviourGuide) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{3} }

func (m *BehaviourGuide) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourGuide) GetGuideId() int32 {
	if m != nil && m.GuideId != nil {
		return *m.GuideId
	}
	return 0
}

// 日志行为：经验
type BehaviourExp struct {
	UserId           *int32 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Exp              *int32 `protobuf:"varint,3,req,name=exp" json:"exp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BehaviourExp) Reset()                    { *m = BehaviourExp{} }
func (m *BehaviourExp) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourExp) ProtoMessage()               {}
func (*BehaviourExp) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{4} }

func (m *BehaviourExp) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourExp) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *BehaviourExp) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

// 日志行为：推图进度
type BehaviourBattle struct {
	UserId           *int32 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	BattleId         *int32 `protobuf:"varint,2,req,name=battleId" json:"battleId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BehaviourBattle) Reset()                    { *m = BehaviourBattle{} }
func (m *BehaviourBattle) String() string            { return proto1.CompactTextString(m) }
func (*BehaviourBattle) ProtoMessage()               {}
func (*BehaviourBattle) Descriptor() ([]byte, []int) { return behaviour_log_fileDescriptor0, []int{5} }

func (m *BehaviourBattle) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *BehaviourBattle) GetBattleId() int32 {
	if m != nil && m.BattleId != nil {
		return *m.BattleId
	}
	return 0
}

func init() {
	proto1.RegisterType((*Behaviour)(nil), "Behaviour")
	proto1.RegisterType((*BehaviourCreateRole)(nil), "BehaviourCreateRole")
	proto1.RegisterType((*BehaviourView)(nil), "BehaviourView")
	proto1.RegisterType((*BehaviourGuide)(nil), "BehaviourGuide")
	proto1.RegisterType((*BehaviourExp)(nil), "BehaviourExp")
	proto1.RegisterType((*BehaviourBattle)(nil), "BehaviourBattle")
	proto1.RegisterEnum("BehaviourType", BehaviourType_name, BehaviourType_value)
}

var behaviour_log_fileDescriptor0 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0x4b, 0x4f, 0xea, 0x40,
	0x1c, 0xc5, 0xd3, 0xc7, 0x14, 0x38, 0x40, 0x99, 0x0c, 0x77, 0xd1, 0xdc, 0x7b, 0x73, 0x43, 0xba,
	0x6a, 0xee, 0xa2, 0x46, 0x8c, 0x1b, 0x97, 0x35, 0xc4, 0x90, 0xb8, 0x32, 0xc6, 0x85, 0x1b, 0x52,
	0xca, 0x08, 0x4d, 0x8a, 0x53, 0xeb, 0xf0, 0xf0, 0x53, 0xfa, 0x95, 0x9c, 0x4e, 0x03, 0x85, 0xea,
	0x72, 0xce, 0xf9, 0x3f, 0xce, 0xef, 0xdf, 0x62, 0x38, 0xe7, 0xab, 0x78, 0x9b, 0x8a, 0x4d, 0x31,
	0xcb, 0xc4, 0x32, 0xcc, 0x0b, 0x21, 0x85, 0xff, 0x69, 0xa0, 0x13, 0x1d, 0x74, 0xf6, 0x17, 0xb6,
	0xfc, 0xc8, 0xb9, 0x67, 0x8c, 0xcc, 0xc0, 0x1d, 0xbb, 0xe1, 0xd1, 0x79, 0x54, 0x2a, 0x0b, 0x80,
	0xa4, 0xe0, 0xb1, 0xe4, 0x0f, 0x22, 0xe3, 0x9e, 0x39, 0x32, 0x82, 0xee, 0xf8, 0x57, 0x5d, 0x73,
	0x7b, 0xf4, 0xca, 0x39, 0xdb, 0x94, 0xef, 0x3c, 0x4b, 0xd7, 0x9c, 0xcc, 0x79, 0x52, 0x2a, 0xfb,
	0x07, 0xb2, 0xdc, 0xa4, 0x0b, 0xee, 0xd9, 0xda, 0x1e, 0xd4, 0xf6, 0x5d, 0x29, 0xb3, 0xdf, 0xb0,
	0xf8, 0x3e, 0xf7, 0x88, 0x76, 0xfb, 0xb5, 0x3b, 0xd9, 0xe7, 0x6c, 0x04, 0x67, 0x1e, 0x4b, 0xa9,
	0xf6, 0x3b, 0xda, 0xa6, 0xb5, 0x1d, 0x69, 0xdd, 0x9f, 0x60, 0xf8, 0x53, 0x24, 0x17, 0xce, 0xe6,
	0x9d, 0x17, 0xd3, 0x85, 0x86, 0x23, 0xac, 0x07, 0xfb, 0x35, 0x5e, 0x97, 0x18, 0x66, 0xd0, 0x61,
	0x14, 0xed, 0x3c, 0x8b, 0xe5, 0x8b, 0x28, 0xd6, 0x2a, 0xb4, 0x52, 0xfc, 0x0b, 0xf4, 0xcf, 0x53,
	0x37, 0x07, 0xa8, 0x77, 0xc9, 0xa8, 0xde, 0xe5, 0x08, 0xe2, 0x5f, 0xc2, 0x6d, 0x70, 0x34, 0x3b,
	0x06, 0x68, 0x69, 0xee, 0x63, 0xcb, 0x0d, 0x7a, 0x67, 0x70, 0xcd, 0x86, 0x3e, 0x48, 0xc6, 0xb7,
	0x3c, 0xab, 0xca, 0x59, 0xb7, 0xba, 0x8b, 0xa5, 0x7b, 0xaf, 0x30, 0x68, 0x90, 0x7f, 0x6b, 0x57,
	0x50, 0xd5, 0xad, 0x0e, 0x0b, 0xff, 0x4f, 0x4f, 0xa0, 0xf4, 0x27, 0x75, 0x81, 0xfa, 0x46, 0xd4,
	0x60, 0x6d, 0xd8, 0x25, 0x2c, 0x35, 0x59, 0x07, 0x44, 0x53, 0x50, 0x8b, 0xb5, 0x60, 0xa9, 0x74,
	0xd4, 0x66, 0x80, 0x53, 0xad, 0xa2, 0x24, 0xba, 0xc6, 0x9f, 0x44, 0xac, 0xc3, 0xb7, 0x34, 0x09,
	0x77, 0xa2, 0xc8, 0x16, 0x3b, 0x55, 0x9b, 0xac, 0x62, 0x59, 0xfd, 0x57, 0x51, 0x1d, 0xee, 0x5e,
	0x2c, 0x67, 0xf9, 0xfc, 0x99, 0x68, 0xfd, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x0b, 0x6b, 0x92,
	0x85, 0x02, 0x00, 0x00,
}
