// Code generated by protoc-gen-go.
// source: chat_msg.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	chat_msg.proto

It has these top-level messages:
	ChatMsg
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

// 聊天消息
type ChatMsg struct {
	UserId           *int32  `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	Vip              *int32  `protobuf:"varint,2,req,name=vip" json:"vip,omitempty"`
	ZoneName         *string `protobuf:"bytes,3,opt,name=zoneName" json:"zoneName,omitempty"`
	Name             *string `protobuf:"bytes,4,req,name=name" json:"name,omitempty"`
	Msg              *string `protobuf:"bytes,5,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatMsg) Reset()                    { *m = ChatMsg{} }
func (m *ChatMsg) String() string            { return proto1.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()               {}
func (*ChatMsg) Descriptor() ([]byte, []int) { return chat_msg_fileDescriptor0, []int{0} }

func (m *ChatMsg) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ChatMsg) GetVip() int32 {
	if m != nil && m.Vip != nil {
		return *m.Vip
	}
	return 0
}

func (m *ChatMsg) GetZoneName() string {
	if m != nil && m.ZoneName != nil {
		return *m.ZoneName
	}
	return ""
}

func (m *ChatMsg) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ChatMsg) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto1.RegisterType((*ChatMsg)(nil), "ChatMsg")
}

var chat_msg_fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0x48, 0x2c,
	0x89, 0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe6, 0x62, 0x77, 0x06,
	0x8a, 0xf8, 0x16, 0xa7, 0x0b, 0xf1, 0x71, 0xb1, 0x95, 0x16, 0xa7, 0x16, 0x79, 0xa6, 0x48, 0x30,
	0x2a, 0x30, 0x69, 0xb0, 0x0a, 0x71, 0x73, 0x31, 0x97, 0x65, 0x16, 0x48, 0x30, 0x81, 0x39, 0x02,
	0x5c, 0x1c, 0x55, 0xf9, 0x79, 0xa9, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x9c,
	0x42, 0x3c, 0x5c, 0x2c, 0x79, 0x20, 0x1e, 0x0b, 0x50, 0x9e, 0x13, 0xa4, 0x18, 0x68, 0xa8, 0x04,
	0x2b, 0x88, 0xe3, 0x64, 0xc0, 0x25, 0x9d, 0x9c, 0x9f, 0xab, 0x57, 0x98, 0x99, 0xac, 0x57, 0x9e,
	0x5f, 0x94, 0x93, 0x52, 0x9e, 0x99, 0x92, 0x0a, 0xb2, 0x17, 0x62, 0xa7, 0x13, 0x17, 0xd4, 0xc6,
	0xf8, 0x82, 0xa4, 0x28, 0x56, 0xb0, 0x10, 0x20, 0x00, 0x00, 0xff, 0xff, 0x28, 0x35, 0x75, 0xab,
	0x97, 0x00, 0x00, 0x00,
}
